### ISSUE TITLE
파이썬 어떤 버전에서 썼는지 알 수 있을까요?

### ISSUE THREAD

**Issue by leewoojye** [yeonsikch/nlp-filter-out#1]
requirments.txt 파일에 있는 패키지를 모두 다운받으려면 특정한 버전의 파이썬을 사용해야할 거 같아서 질문드립니다

**Comment by yeonsikch** [comment]
안녕하세요.

정확히 기억은 나지 않지만 제가 평소에 python 3.7 버전을 사용하니
해당 버전을 사용하시면 될 것 같습니다.

그리고, 해당 코드가 깔끔하게 에러가 나지 않는다고 장담할 순 없을 것 같습니다.
약간의 디버깅의 시간을 가져야할 수도 있습니다.

감사합니다.

**Comment by leewoojye** [comment]
답변 정말 감사합니다 ㅜ
한가지 더 여쭙고 싶은게 있어요
프로젝트에 필요한 파이썬 패키지를 모두 설치했는데 주피터노트북 파일 여러개를 한번에 실행할 수 없나요?
inference 파일에서 입력을 하면 바로 출력을 얻고 싶습니다..ㅜ

네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2022. 6. 10 18:20:59
제목: Re: [yeonsikch/nlp-filter-out] 파이썬 어떤 버전에서 썼는지 알 수 있을까요? (Issue #1)

안녕하세요.
정확히 기억은 나지 않지만 제가 평소에 python 3.7 버전을 사용하니
해당 버전을 사용하시면 될 것 같습니다.
그리고, 해당 코드가 깔끔하게 에러가 나지 않는다고 장담할 순 없을 것 같습니다.
약간의 디버깅의 시간을 가져야할 수도 있습니다.
감사합니다.

**Comment by yeonsikch** [comment]
주피터 노트북은 실행 환경이, 마치 크롬에서 여러 tab을 띄우듯이 하는것이라
여러개를 한번에 실행하실 수 있습니다.

다만, GPU를 사용할 경우에는 CUDA OOM(Out-Of-Memory)가 발생하지않도록 주의하셔야해요.

**Comment by leewoojye** [comment]
참고하겠습니다! 감사합니다 ㅜ 
실례지만 학교 프로젝트와 관련이 있어서 몇가지 더 여쭙고 싶어요.. 
우선 mxnet 패키지 1.8.0.post0 를 설치하라고 하셨는데 제가 파이썬 3.8.6으로 돌려서 그런지 모르겠는데 1.8.0.post 버전이 없다고 떠요..
그리고 inference.ipynb 파일에서 모두 실행 버튼(vscode 사용하고 있어요)을 누르면 문장에 대한 출력이 나오는걸 테스트 할 수 있는건지 궁금합니다(주피터 노트북 프로젝트를 처음 다루어봐서요ㅜㅜㅜ)
답변 주신다면 정말 감사하겠습니다! ㅜㅜ


네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2022. 6. 10 20:34:10
제목: Re: [yeonsikch/nlp-filter-out] 파이썬 어떤 버전에서 썼는지 알 수 있을까요? (Issue #1)

주피터 노트북은 실행 환경이, 마치 크롬에서 여러 tab을 띄우듯이 하는것이라
여러개를 한번에 실행하실 수 있습니다.
다만, GPU를 사용할 경우에는 CUDA OOM(Out-Of-Memory)가 발생하지않도록 주의하셔야해요.

**Comment by leewoojye** [comment]
아! 그리고 kobert 패키지는 SKTBrain/KoBERT: Korean BERT pre-trained cased (KoBERT) (github.com) 에서 가져오신게 맞을까요?!
질문 많은 점 죄송합니다..
-----Original Message-----

**Comment by yeonsikch** [comment]
pip install mxnet==1.8.0.post 버전이 없다면 그 이전이나 이후 버전을 설치하시고서 에러가 안나는 버전을 설치하시면 될 것 같습니다. 제 생각에는 python version과는 크게 상관이 없을것으로 생각됩니다.

vscode에서 모두 실행 버튼 누르면 입력에 대한 출력이 나오지만, 내부적으로 경로라든가 수정해야할 부분이 분명 존재할거에요.

SKTBrain/KoBERT 관련해서는 제가 정확히 기억은 안나지만 아마 github에서 가져오지않았나 생각합니다.

**Comment by yeonsikch** [comment]
현재, check_point 폴더에 gru 모델에 대한 가중치 파일만 업로드 되어있습니다.(용량 제한)
따라서, KoBERT를 사용하시려면 Kobert trainer.ipynb 파일을 통해 학습하시고 inference 하셔야 합니다.

**Comment by leewoojye** [comment]
자세한 답변 감사합니다 ! 참고해서 시도해보겠습니다 


네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2022. 6. 11 14:10:36
제목: Re: [yeonsikch/nlp-filter-out] 파이썬 어떤 버전에서 썼는지 알 수 있을까요? (Issue #1)

현재, check_point 폴더에 gru 모델에 대한 가중치 파일만 업로드 되어있습니다.(용량 제한)
따라서, KoBERT를 사용하시려면 Kobert trainer.ipynb 파일을 통해 학습하시고 inference 하셔야 합니다.

**Comment by leewoojye** [comment]
하나만 더 여쭤봐도 될까요 ㅜㅜ 윈도우 운영체제에서도 프로젝트를 실행할 수 있나요..? 

네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2022. 6. 11 14:09:03
제목: Re: [yeonsikch/nlp-filter-out] 파이썬 어떤 버전에서 썼는지 알 수 있을까요? (Issue #1)

pip install mxnet==1.8.0.post 버전이 없다면 그 이전이나 이후 버전을 설치하시고서 에러가 안나는 버전을 설치하시면 될 것 같습니다. 제 생각에는 python version과는 크게 상관이 없을것으로 생각됩니다.
vscode에서 모두 실행 버튼 누르면 입력에 대한 출력이 나오지만, 내부적으로 경로라든가 수정해야할 부분이 분명 존재할거에요.
SKTBrain/KoBERT 관련해서는 제가 정확히 기억은 안나지만 아마 github에서 가져오지않았나 생각합니다.

**Comment by yeonsikch** [comment]
windows에서 작업한 파일입니다.

**Comment by leewoojye** [comment]
안녕하세요 한가지 더 여쭙고 싶어요..
trainer 파일에 chardataset 클래에 있는 tok_path = '/home/yeonsik/kobert/kobert_news_wiki_ko_cased-1087f8699e.spiece'
이 무슨 뜻인지 알 수 있을까요?... 아까 수정하라고 하신 경로가 이건 것 같아서요 ㅜ
﻿ 
-----Original Message-----

**Comment by yeonsikch** [comment]
https://github.com/SKTBrain/KoBERT/issues/47

해당 파일을 어디에선가 다운로드를 받은뒤에 해당 경로를 입력해야됩니다.
해당 파일이 어디에서 배포되는지는 찾아보셔야할것같습니다.
